// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Collapse: typeof import("./src/components/Collapse/index.vue")["default"];
    Column: typeof import("./src/components/FormTable/Column.vue")["default"];
    DefaultFallback: typeof import("./src/components/ErrorBoundary/DefaultFallback.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLoading: typeof import("element-plus/es")["ElLoading"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElSubmenu: typeof import("element-plus/es")["ElSubmenu"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ErrorBoundary: typeof import("./src/components/ErrorBoundary/ErrorBoundary.vue")["default"];
    Form: typeof import("./src/components/FormTable/Form.vue")["default"];
    FormTable: typeof import("./src/components/FormTable/index.vue")["default"];
    FormTraversal: typeof import("./src/components/Traversal/FormTraversal.vue")["default"];
    GenericsTraversal: typeof import("./src/components/Traversal/GenericsTraversal.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    NormalizeButton: typeof import("./src/components/Button/NormalizeButton.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Table: typeof import("./src/components/FormTable/Table.vue")["default"];
    Traversal: typeof import("./src/components/Traversal/Traversal.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
