// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Traversal: typeof import("./src/components/Traversal/Traversal.vue")["default"];
    VanButton: typeof import("vant/es")["Button"];
    VanCalendar: typeof import("vant/es")["Calendar"];
    VanCell: typeof import("vant/es")["Cell"];
    VanConfigProvider: typeof import("vant/es")["ConfigProvider"];
    VanNavBar: typeof import("vant/es")["NavBar"];
    VanNumberKeyboard: typeof import("vant/es")["NumberKeyboard"];
  }
}
