export const StatusCodeMap: Record<string | number, string> = {
  200: "The server successfully returned the requested data.",
  201: "New or modified data is successful.",
  202: "A request has entered the background queue (asynchronous task).",
  204: "Delete data successfully.",
  400: "There was an error in the request sent, and the server did not create or modify data.",
  401: "The user does not have permission (token, username, password error).",
  403: "The user is authorized, but access is forbidden.",
  404: "The request sent was for a record that did not exist, and the server did not operate.",
  406: "The requested format is not available.",
  410: "The requested resource is permanently deleted and will not be obtained again.",
  422: "When creating an object, a validation error occurred.",
  500: "An error occurred on the server. Please check the server.",
  502: "Gateway error.",
  503: "The service is unavailable, the server is temporarily overloaded or maintained.",
  504: "The gateway timed out.",
  505: "The server has been temporarily unavailable.",
  510: "The server has been temporarily unavailable due to its internal issue.",
};
